# Generated by Django 4.2.5 on 2023-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0003_alter_spotifytoken_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=150),
        ),
    ]
