# Generated by Django 4.2.5 on 2023-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0004_alter_spotifytoken_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
